# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('user_created', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('users', models.ManyToManyField(to='belt_test.Users')),
            ],
        ),
    ]
